### ISSUE TITLE
Custom Workbench Dupe

### ISSUE THREAD

**Issue by Equalzzz** [LeonidMem/CoreM#4]
**Я нащел дюп с кастомным верстаком:**
1. Ставишь кастомный верстак и под ним ломаешь блок.
2. Встаешь вплотную к верстаку к одной из его сторон (кроме верхней или нижней) и ломаешь под собой блок.
3. В верстаке выкладываешь любой кастомный рецепт и выходишь из интерфейса.
4. Сзади себя ставишь и поджигаешь динамит.
5. Спринтишь без остановки в сторону верстака.

После совершения этих действий выпадает верстак, предметы, которые ты туда положил и результат крафта (разумеется с тегом)
Результат не успевает удалится (в ввиде энтити) и сразу попадает в инвентарь.

P.s конечно можно удалять эти предметы командой /clear, а не только /kill, но я так понимаю это дело уже только того человека, который делает датапак, используя coreM.

**Comment by LeonidMem** [comment]
Fixed
